INSERT INTO CURRENCY_EXCHANGE (ID,CURRENCY_FROM,CURRENCY_TO,CONVERSION_MULTIPLE,ENVIRONMENT)
VALUES (10001,'USD','INR',70,'8000');

INSERT INTO CURRENCY_EXCHANGE (ID,CURRENCY_FROM,CURRENCY_TO,CONVERSION_MULTIPLE,ENVIRONMENT)
VALUES (10002,'EUR','INR',90,'8000');

INSERT INTO CURRENCY_EXCHANGE (ID,CURRENCY_FROM,CURRENCY_TO,CONVERSION_MULTIPLE,ENVIRONMENT)
VALUES (10003,'AUD','INR',50,'8000');